USE base_lumhome;
-- REM **************************************************************************
-- REM Base : BASE_LUMHOME
-- REM Auteur : Mathieu VALENTIN
-- REM Group : G2B
-- REM Date de Mise à Jour : 25/10/2018
-- REM **************************************************************************

-- REM ************************* DROP *******************************************
DROP TABLE IF EXISTS PARAMETRE ;
DROP TABLE IF EXISTS SCENARIO_UTILISATEUR ;
DROP TABLE IF EXISTS SCENARIO_CEMAC ;
DROP TABLE IF EXISTS CEMAC ;
DROP TABLE IF EXISTS PIECE ;
DROP TABLE IF EXISTS SCENARIO ;
DROP TABLE IF EXISTS HABITAT ;
DROP TABLE IF EXISTS UTILISATEUR ;

-- DROP SEQUENCE IF EXISTS UTILISATEUR_SEQ;
-- DROP SEQUENCE IF EXISTS HABITAT_SEQ;
-- DROP SEQUENCE IF EXISTS PIECE_SEQ;
-- DROP SEQUENCE IF EXISTS SCENARIO_SEQ;
-- DROP SEQUENCE IF EXISTS CEMAC_SEQ;
-- DROP SEQUENCE IF EXISTS PARAMETRE_SEQ;
-- -- REM ************************* FIN DROP ***************************************

-- -- REM ************************* SEQUENCES **************************************
-- CREATE SEQUENCE UTILISATEUR_SEQ START WITH 0 INCREMENTS BY 1 NOCACHE NOCYCLE
-- ;
-- CREATE SEQUENCE HABITAT_SEQ START WITH 0 INCREMENTS BY 1 NOCACHE NOCYCLE
-- ;
-- CREATE SEQUENCE PIECE_SEQ START WITH 0 INCREMENTS BY 1 NOCACHE NOCYCLE
-- ;
-- CREATE SEQUENCE SCENARIO_SEQ START WITH 0 INCREMENTS BY 1 NOCACHE NOCYCLE
-- ;
-- CREATE SEQUENCE CEMAC_SEQ START WITH 0 INCREMENTS BY 1 NOCACHE NOCYCLE
-- ;
-- CREATE SEQUENCE PARAMETRE_SEQ START WITH 0 INCREMENTS BY 1 NOCACHE NOCYCLE
-- ;
-- REM ************************* FIN SEQUENCES **********************************

-- REM ************************* TABLES *****************************************
-- REM ***** CREATE TABLE UTILISATEUR
CREATE TABLE UTILISATEUR (
    adresseMail VARCHAR(30),
    nomUser VARCHAR (15) NOT NULL,
    prenomUser VARCHAR(15) NOT NULL,
    adresseFacturation INT(11),
    type VARCHAR(20) NOT NULL,
    mdpUser INT(30) NOT NULL,
    pin INT(4),
    numeroCarte INT(16),
	cryptogramme INT(3),
	dateExpiration DATE
)ENGINE=InnoDB  CHARACTER SET utf8 COLLATE utf8_bin;

-- REM ***** CREATE TABLE HABITAT
CREATE TABLE HABITAT (
	idHabitat INT(11),
	nomHabitat VARCHAR(20) NOT NULL,
    numero INT(11) NOT NULL,
	rue VARCHAR(50) NOT NULL,
    complement VARCHAR(255) NOT NULL,
	ville VARCHAR(50) NOT NULL,
	codePostal INT(5) NOT NULL,
    fk_proprietaire VARCHAR(30)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin;

-- REM ***** CREATE TABLE PIECE
CREATE TABLE PIECE (
	idPiece INT(11),
	type VARCHAR(20) NOT NULL,
    nom VARCHAR(20) NOT NULL,
    fk_habitat INT(11)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin;

-- REM ***** CREATE TABLE SCENARIO
CREATE TABLE SCENARIO (
	nom VARCHAR(20),
    dateDebut TIMESTAMP,
    dateFin TIMESTAMP,
    statut BOOLEAN NOT NULL,
    scenario VARCHAR(30) NOT NULL,
    type VARCHAR(30) NOT NULL
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin;

-- REM ***** CREATE TABLE CEMAC
CREATE TABLE CEMAC (
    numeroSerie VARCHAR(30),
	adresseMac CHAR(12) NOT NULL,
	type VARCHAR(10) NOT NULL,
	panne BOOLEAN NOT NULL,
    fk_piece INT(11)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin;

-- REM ***** CREATE TABLE PARAMETRE
CREATE TABLE PARAMETRE (
	type VARCHAR(20),
    fk_CeMAC VARCHAR(30),
	valeur VARCHAR(20) NOT NULL
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin;

-- REM ***** CREATE TABLE SCENARIO_UTILISATEUR
CREATE TABLE SCENARIO_UTILISATEUR (
    fk_scenario VARCHAR(20),
    fk_proprietaire VARCHAR(30)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin;

-- REM ***** CREATE TABLE SCENARIO_CEMAC
CREATE TABLE SCENARIO_CEMAC (
    fk_scenario VARCHAR(20),
    fk_CeMAC VARCHAR(30),
    valeurIntensite INT(11),
    valeurCouleur CHAR(6)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin;
-- REM ************************* FIN TABLES *************************************

-- REM ************************* CONSTRAINTS ************************************
-- REM ***** UTILISATEUR
ALTER TABLE UTILISATEUR ADD CONSTRAINT PK_UTILISATEUR PRIMARY KEY (adresseMail)
;
ALTER TABLE HABITAT ADD CONSTRAINT PK_HABITAT PRIMARY KEY (idHabitat)
;
ALTER TABLE PIECE ADD CONSTRAINT PK_PIECE PRIMARY KEY (idPiece)
;
ALTER TABLE CEMAC ADD CONSTRAINT PK_CEMAC PRIMARY KEY (numeroSerie)
;
ALTER TABLE PARAMETRE ADD CONSTRAINT PK_PARAMETRE PRIMARY KEY (type)
;
ALTER TABLE SCENARIO ADD CONSTRAINT PK_SCENARIO PRIMARY KEY (nom)
;
ALTER TABLE SCENARIO_UTILISATEUR ADD CONSTRAINT PK_SCENARIO_UTILISATEUR PRIMARY KEY (fk_scenario, fk_proprietaire)
;
ALTER TABLE SCENARIO_CEMAC ADD CONSTRAINT PK_SCENARIO_CEMAC PRIMARY KEY (fk_scenario, fk_CeMAC)
;

-- REM ***** HABITAT

ALTER TABLE HABITAT ADD CONSTRAINT FK_HABITAT_UTILISATEUR FOREIGN KEY (fk_proprietaire) REFERENCES UTILISATEUR(adresseMail) ON DELETE CASCADE
;
-- REM ***** PIECE

ALTER TABLE PIECE ADD CONSTRAINT FK_PIECE_HABITAT FOREIGN KEY (fk_habitat) REFERENCES HABITAT(idHabitat) ON DELETE CASCADE
;

-- REM ***** SCENARIO


-- REM ***** CEMAC

ALTER TABLE CEMAC ADD CONSTRAINT FK_CEMAC_PIECE FOREIGN KEY (fk_piece) REFERENCES PIECE(idPiece) ON DELETE CASCADE
;

-- REM ***** PARAMETRE

ALTER TABLE PARAMETRE ADD CONSTRAINT FK_PARAMETRE_CEMAC FOREIGN KEY (fk_CeMAC) REFERENCES CEMAC(numeroSerie) ON DELETE CASCADE
;

-- REM ***** SCENARIO_UTILISATEUR
ALTER TABLE SCENARIO_UTILISATEUR ADD CONSTRAINT FK_SCENARIO_UTILISATEUR_SCENARIO FOREIGN KEY (fk_scenario) REFERENCES SCENARIO(nom) ON DELETE CASCADE
;
ALTER TABLE SCENARIO_UTILISATEUR ADD CONSTRAINT FK_SCENARIO_UTILISATEUR_UTILISATEUR FOREIGN KEY (fk_proprietaire) REFERENCES UTILISATEUR(adresseMail) ON DELETE CASCADE
;


-- REM ***** SCENARIO_CEMAC
ALTER TABLE SCENARIO_CEMAC ADD CONSTRAINT FK_SCENARIO_CEMAC_SCENARIO FOREIGN KEY (fk_scenario) REFERENCES SCENARIO(nom) ON DELETE CASCADE
;
ALTER TABLE SCENARIO_CEMAC ADD CONSTRAINT FK_SCENARIO_CEMAC_CEMAC FOREIGN KEY (fk_CeMAC) REFERENCES CEMAC(numeroSerie) ON DELETE CASCADE
;

-- REM ************************* FIN CONSTRAINTS ********************************

-- REM ************************* DATAS ******************************************
-- REM ***** UTILISATEUR
INSERT INTO UTILISATEUR VALUES ();
INSERT INTO UTILISATEUR VALUES ();
INSERT INTO UTILISATEUR VALUES ();
INSERT INTO UTILISATEUR VALUES ();

-- REM ***** HABITAT
INSERT INTO PARAMETRE VALUES ();
INSERT INTO PARAMETRE VALUES ();

-- REM ***** PIECE
INSERT INTO PIECE VALUES ();

-- REM ***** SCENARIO
INSERT INTO SCENARIO VALUES ();

-- REM ***** CEMAc
INSERT INTO CEMAC VALUES ();

-- REM ***** PARAMETRE
INSERT INTO PARAMETRE VALUES ();

-- REM ***** SCENARIO_UTILISATEUR
INSERT INTO SCENARIO_UTILISATEUR VALUES ();

-- REM ***** SCENARIO_CEMAC
INSERT INTO SCENARIO_CEMAC VALUES ();
-- REM ************************* FIN DATAS **************************************